version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app          # Mount code for live changes
      - backend_venv:/opt/venv  # Persist virtualenv
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app          # Mount code for live changes
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:80"                # React served via nginx
    environment:
      - CHOKIDAR_USEPOLLING=true # For live reload on Docker

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  backend_venv:
  frontend_node_modules:
  postgres_data:
